# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudmanager < Formula
  desc "Manage your cloud resources from the terminal."
  homepage "https://github.com/vyoogam/cloudmanager"
  version "1.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/vyoogam/cloudmanager/releases/download/v1.0.0/cloudmanager_Darwin_all.tar.gz"
    sha256 "b793aef41c1701999b70525140cdc076f9b3f86cbc4358752977939f9a0643fe"

    define_method(:install) do
      bin.install "cloudmanager"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vyoogam/cloudmanager/releases/download/v1.0.0/cloudmanager_Linux_x86_64.tar.gz"
      sha256 "7cf224681bf4d660d11dd9471109776e9b10bf2c2c671bd6faabb417678d0c1d"
      define_method(:install) do
        bin.install "cloudmanager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vyoogam/cloudmanager/releases/download/v1.0.0/cloudmanager_Linux_arm64.tar.gz"
      sha256 "5b706bfc9a083068b13ac1437277f26d623af8c4e14a41e3532c62c46054d344"
      define_method(:install) do
        bin.install "cloudmanager"
      end
    end
  end

  test do
    system "#{bin}/cloudmanager", "--version"
  end
end
